# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-dev.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make init

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-dev.txt" }}

      - run:
          name: run pytest and generate reports
          command: |
            . venv/bin/activate
            make test-behave-reports

      - run:
          name: run behave tests
          command: |
            . venv/bin/activate
            make test-behave

      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports